### ISSUE TITLE
Regression when candid is running in a sub-location

### ISSUE THREAD

**Issue by stgraber** [canonical/candid#25]
According to a quick bisect I did, 99d8505e3e5dfbba061b7db81b84330defe55a48 is breaking Candid for anyone who's not running it at the root of their domain.

In my case, my `location` is set to `https://services.stgraber.org/identity`. Any login attempt since that commit immediately fails with `Login failed: invalid login state`.

Looking at the commit, I suspect the cookie path needs to be updated to take the location into consideration.

@mhilton

**Comment by stgraber** [comment]
@sdeziel for awareness, this is what's breaking NorthSec.
@tomponline for awareness, this is what's breaking MAAS/LXD auth.

**Comment by stgraber** [comment]
I've rebuild candid locally using:
```diff
diff --git a/idp/idputil/idputil.go b/idp/idputil/idputil.go
index 881c384..e251e50 100644
--- a/idp/idputil/idputil.go
+++ b/idp/idputil/idputil.go
@@ -142,7 +142,7 @@ const LoginCookieName = "candid-login"
 
 // LoginCookiePath is the path to associate with the cookie storing the
 // current login state.
-const LoginCookiePath = "/login"
+const LoginCookiePath = "/identity/login"
 
 // LoginState holds the state of the current loging process.
 type LoginState struct {
diff --git a/internal/discharger/login.go b/internal/discharger/login.go
index 251d7cb..d14854b 100644
--- a/internal/discharger/login.go
+++ b/internal/discharger/login.go
@@ -74,7 +74,7 @@ func (h *handler) Login(p httprequest.Params, req *loginRequest) error {
        // Store the requested discharge ID in a session cookie so that
        // when the redirect comes back to login-complete we know the
        // login was initiated in this session.
-       state, err := h.params.codec.SetCookie(p.Response, waitCookieName, "/login-complete", waitState{
+       state, err := h.params.codec.SetCookie(p.Response, waitCookieName, "/identity/login-complete", waitState{
                DischargeID: req.DischargeID,
        })
        if err != nil {
```

And confirmed that our setup works again.

This is obviously not an upstream viable patch, but it's a good enough workaround for now until the snap is fixed and proves that the path is indeed the issue.

**Comment by mhilton** [comment]
Thanks @stgraber sorry for the regression.
