### ISSUE TITLE
Ubuntu SSO backend doesn't respect `http-proxy`

### ISSUE THREAD

**Issue by stgraber** [canonical/candid#51]
Running Candid in an environment where using a proxy is mandatory to access the outside world, I'm getting login errors (connection refused) trying to reach `login.ubuntu.com` directly instead of using the configure proxy (`http-proxy`).

**Comment by mhilton** [comment]
I suspect this is due to the change of behaviour in ProxyFromEnvironment https://golang.org/doc/go1.16#net/http in go 1.16. If you need a quick workaround you'll probably find that setting an explicit `HTTPS_PROXY` environment variable will make things work again until it is fixed.

**Comment by mhilton** [comment]
fixed in release v1.8.1
